//
// Created by MuYao Si on 2021-08-18.
//

#ifndef OPTIONEXACTPRICINGMONTECARLOPRICING_EUROPAYOFF_H
#define OPTIONEXACTPRICINGMONTECARLOPRICING_EUROPAYOFF_H

#include "path.h"

class EuroPayOff:public path {

};


#endif //OPTIONEXACTPRICINGMONTECARLOPRICING_EUROPAYOFF_H
